### ISSUE TITLE
Issue: Abourting group conversion

### ISSUE THREAD

**Issue by synuhaan** [DSlyDog/Universes-Rewritten#3]
when doing the /convert command, i get the ABOURTING GROUP CONVERSION error

Something to do with groups.yml:
```
world:
  group: world
world_nether:
  group: world
world_the_end:
  group: world
SecondWorld_the_end:
  group: SecondWorld
NewUniverse_nether:
- NewUniverse_nether
NewUniverse_the_end:
- NewUniverse_the_end
NewUniverse:
- NewUniverse
default:
- world
- world_nether
- world_the_end
```
